FORMAT: v1
HOST: http://localhost/

# Flash 

## Error States

遵循 [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) 标准.

## Goods [/prode/]
Get Goods list 

### Retrieve Goods [GET]

+ Response 200 (application/json)
  + Attributes (Goods)

# Data Structures

## Goods
+　
  + name: `mary` (string)
  + department: `Operation` (string)
  + photo: `/media/photo/mary.jpg` (string)
